In [2]:
def coefficient_of_variation(x):
    return x.std() / x.mean() if x.mean() != 0 else 0

# vLLM CG-Only

In [ ]:
import pandas as pd
# 개별 CSV 파일 읽기
df1 = pd.read_csv("./amd/vllm_offline_nps4_v1_graphFULL_cc_5000_2025-12-06/vllm_offline_nps4_cc_2025-12-06.csv")
df2 = pd.read_csv("./amd/vllm_offline_nps4_v1_graphFULL_cc_5000_2025-12-09/vllm_offline_nps4_cc_2025-12-09.csv")

# 리스트에 추가
df_list = [df1, df2]

# 병합
merged_df = pd.concat(df_list, ignore_index=True)

output_csv = "vllm_offline_nps4_graphFULL_cc_5000_merged.csv"
# 저장
merged_df.to_csv(output_csv, index=False)

In [5]:
import pandas as pd

# CSV 파일 읽기
df = pd.read_csv("vllm_offline_nps4_graphFULL_cc_5000_merged.csv")


# 그룹화 및 통계 집계
grouped = df.groupby(['model_path', 'max_num_seqs'])['total_token_throughput'].agg(
    mean_cc='mean',
    min_cc='min',
    max_cc='max',
    std_dev_cc='std',
    cv_cc=coefficient_of_variation
).reset_index()

# 결과 저장
grouped.to_csv("vllm_offline_cuda1_compile0_cc_min_and_max.csv", index=False)
display(grouped)

,model_path,max_num_seqs,mean_cc,min_cc,max_cc,std_dev_cc,cv_cc
0,meta-llama/Llama-3.1-8B,4,720.9000,716.08,727.11,5.644847,0.007830
1,meta-llama/Llama-3.1-8B,8,1405.5400,1399.14,1409.05,5.551225,0.003950
2,meta-llama/Llama-3.1-8B,16,2620.4100,2604.07,2645.30,17.547944,0.006697
3,meta-llama/Llama-3.1-8B,32,4610.1025,4576.76,4669.99,42.414324,0.009200

In [ ]:
import pandas as pd

# CSV 파일 읽기
df = pd.read_csv("./amd/vllm_offline_nps4_v1_graphFULL_noncc_5000_2025-12-07/vllm_offline_nps4_noncc_2025-12-07.csv")


# 그룹화 및 통계 집계
grouped = df.groupby(['model_path', 'max_num_seqs'])['total_token_throughput'].agg(
    mean_noncc='mean',
    min_noncc='min',
    max_noncc='max',
    std_dev_noncc='std',
    cv_noncc=coefficient_of_variation
).reset_index()

# 결과 저장
grouped.to_csv("vllm_offline_cuda1_compile0_noncc_min_and_max.csv", index=False)
display(grouped)

,model_path,max_num_seqs,mean_noncc,min_noncc,max_noncc,std_dev_noncc,cv_noncc
0,meta-llama/Llama-3.1-8B,4,746.33,746.33,746.33,NaN,NaN
1,meta-llama/Llama-3.1-8B,8,1447.40,1447.40,1447.40,NaN,NaN
2,meta-llama/Llama-3.1-8B,16,2689.44,2689.44,2689.44,NaN,NaN
3,meta-llama/Llama-3.1-8B,32,4752.19,4750.57,4753.81,2.291026,0.000482

# vLLM CG+TC

In [2]:
import pandas as pd

# CSV 파일 읽기
df = pd.read_csv("./amd/vllm_offline_nps4_v1_compile1_graphPIECESISE_noncc_5000_2025-12-10/vllm_offline_nps4_noncc_2025-12-10.csv")


# 그룹화 및 통계 집계
grouped = df.groupby(['model_path', 'max_num_seqs'])['total_token_throughput'].agg(
    mean_noncc='mean',
    min_noncc='min',
    max_noncc='max',
    std_dev_noncc='std',
    cv_noncc=coefficient_of_variation
).reset_index()

# 결과 저장
grouped.to_csv("vllm_offline_cuda1_compile1_noncc_min_and_max.csv", index=False)
display(grouped)

,model_path,max_num_seqs,mean_noncc,min_noncc,max_noncc,std_dev_noncc,cv_noncc
0,meta-llama/Llama-3.1-8B,4,756.240000,755.19,757.45,1.138464,0.001505
1,meta-llama/Llama-3.1-8B,8,1468.066667,1465.35,1471.45,3.104164,0.002114
2,meta-llama/Llama-3.1-8B,16,2735.556667,2722.80,2746.83,12.083478,0.004417
3,meta-llama/Llama-3.1-8B,32,4837.850000,4818.32,4869.65,27.777813,0.005742

In [6]:
import pandas as pd

# CSV 파일 읽기
df = pd.read_csv("./amd/vllm_offline_nps4_v1_compile1_graphPIECESISE_cc_5000_2025-12-09/vllm_offline_nps4_cc_2025-12-09.csv")


# 그룹화 및 통계 집계
grouped = df.groupby(['model_path', 'max_num_seqs'])['total_token_throughput'].agg(
    mean_cc='mean',
    min_cc='min',
    max_cc='max',
    std_dev_cc='std',
    cv_cc=coefficient_of_variation
).reset_index()

# 결과 저장
grouped.to_csv("vllm_offline_cuda1_compile1_cc_min_and_max.csv", index=False)
display(grouped)

,model_path,max_num_seqs,mean_cc,min_cc,max_cc,std_dev_cc,cv_cc
0,meta-llama/Llama-3.1-8B,4,736.690000,735.77,737.69,0.962497,0.001307
1,meta-llama/Llama-3.1-8B,8,1430.513333,1425.03,1433.43,4.751929,0.003322
2,meta-llama/Llama-3.1-8B,16,2663.073333,2659.09,2667.73,4.359178,0.001637
3,meta-llama/Llama-3.1-8B,32,4748.446667,4712.75,4789.75,38.804974,0.008172

# SGLang Eager

In [ ]:
import pandas as pd

# CSV 파일 읽기
df = pd.read_csv("../offline/amd/sglang_offline_nps4_cc_5000_2025-11-24/sglang_offline_discuda_nps4_cc_2025-11-24.csv")


# 그룹화 및 통계 집계
grouped = df.groupby(['model_path', 'max_num_seqs'])['total_token_throughput'].agg(
    mean_cc='mean',
    min_cc='min',
    max_cc='max',
    std_dev_cc='std',
    cv_cc=coefficient_of_variation
).reset_index()

# 결과 저장
grouped.to_csv("sglang_offline_cuda0_compile0_cc_min_and_max.csv", index=False)

In [7]:
import pandas as pd

# CSV 파일 읽기
df = pd.read_csv("../offline/amd/sglang_offline_nps4_noncc_5000_2025-11-24/sglang_offline_discuda_nps4_noncc_2025-11-24.csv")


# 그룹화 및 통계 집계
grouped = df.groupby(['model_path', 'max_num_seqs'])['total_token_throughput'].agg(
    mean_noncc='mean',
    min_noncc='min',
    max_noncc='max',
    std_dev_noncc='std',
    cv_noncc=coefficient_of_variation
).reset_index()

# 결과 저장
grouped.to_csv("sglang_offline_cuda0_compile0_noncc_min_and_max.csv", index=False)

In [8]:
import pandas as pd

# 두 개의 CSV 파일 읽기
df1 = pd.read_csv("sglang_offline_cuda0_compile0_noncc_min_and_max.csv")
df2 = pd.read_csv("sglang_offline_cuda0_compile0_cc_min_and_max.csv")

sglag_cuda0_compile0_df = pd.merge(df1, df2, on=['model_path', 'max_num_seqs'], how='inner')
# cc_overhead 열 추가: mean_noncc / mean_cc
sglag_cuda0_compile0_df['cc_overhead'] = sglag_cuda0_compile0_df['mean_noncc'] / sglag_cuda0_compile0_df['mean_cc']
sglag_cuda0_compile0_df['min_cc_overhead'] = sglag_cuda0_compile0_df['min_noncc'] / sglag_cuda0_compile0_df['min_cc']
sglag_cuda0_compile0_df['max_cc_overhead'] = sglag_cuda0_compile0_df['max_noncc'] / sglag_cuda0_compile0_df['max_cc']
# 결과 확인
#print(sglag_cuda0_compile0_df[['model_path', 'max_num_seqs', 'mean_noncc', 'mean_cc', 'cc_overhead']].head())
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
print(sglag_cuda0_compile0_df.columns)
print(sglag_cuda0_compile0_df[['model_path','max_num_seqs','mean_cc','cv_cc']])

Index(['model_path', 'max_num_seqs', 'mean_noncc', 'min_noncc', 'max_noncc',
       'std_dev_noncc', 'cv_noncc', 'mean_cc', 'min_cc', 'max_cc',
       'std_dev_cc', 'cv_cc', 'cc_overhead', 'min_cc_overhead',
       'max_cc_overhead'],
      dtype='object')
                model_path  max_num_seqs  mean_cc  cv_cc
0  meta-llama/Llama-3.1-8B             4   321.78    NaN
1  meta-llama/Llama-3.1-8B             8   669.27    NaN
2  meta-llama/Llama-3.1-8B            16  1326.92    NaN
3  meta-llama/Llama-3.1-8B            32  2421.25    NaN

In [9]:
display(sglag_cuda0_compile0_df[['model_path', 'max_num_seqs', 'mean_cc', 
                               'mean_noncc','cv_cc', 'cv_noncc','cc_overhead']])

,model_path,max_num_seqs,mean_cc,mean_noncc,cv_cc,cv_noncc,cc_overhead
0,meta-llama/Llama-3.1-8B,4,321.78,381.48,NaN,NaN,1.185530
1,meta-llama/Llama-3.1-8B,8,669.27,756.40,NaN,NaN,1.130187
2,meta-llama/Llama-3.1-8B,16,1326.92,1445.42,NaN,NaN,1.089305
3,meta-llama/Llama-3.1-8B,32,2421.25,2672.69,NaN,NaN,1.103847

# vLLM Eager

In [8]:
import pandas as pd

# CSV 파일 읽기
df = pd.read_csv("vllm_offline_nps4_v1_cc_5000_2025-11-12/vllm_offline_nps4_cc_2025-11-12.csv")


# 그룹화 및 통계 집계
grouped = df.groupby(['model_path', 'max_num_seqs'])['total_token_throughput'].agg(
    mean_cc='mean',
    min_cc='min',
    max_cc='max',
    std_dev_cc='std',
    cv_cc=coefficient_of_variation
).reset_index()

# 결과 저장
grouped.to_csv("vllm_offline_compile0_cc_min_and_max.csv", index=False)

In [9]:
import pandas as pd

# CSV 파일 읽기
df = pd.read_csv("vllm_offline_nps4_v1_noncc_5000_2025-11-12/vllm_offline_nps4_noncc_2025-11-12.csv")

# 그룹화 및 통계 집계
grouped = df.groupby(['model_path', 'max_num_seqs'])['total_token_throughput'].agg(
    mean_noncc='mean',
    min_noncc='min',
    max_noncc='max',
    std_dev_noncc='std',
    cv_noncc=coefficient_of_variation
).reset_index()

# 결과 저장
grouped.to_csv("vllm_offline_compile0_noncc_min_and_max.csv", index=False)

In [7]:
import pandas as pd

# 두 개의 CSV 파일 읽기
df1 = pd.read_csv("vllm_offline_compile0_noncc_min_and_max.csv")
df2 = pd.read_csv("vllm_offline_compile0_cc_min_and_max.csv")

comile0_df = pd.merge(df1, df2, on=['model_path', 'max_num_seqs'], how='inner')
# cc_overhead 열 추가: mean_noncc / mean_cc
comile0_df['cc_overhead'] = comile0_df['mean_noncc'] / comile0_df['mean_cc']
comile0_df['min_cc_overhead'] = comile0_df['min_noncc'] / comile0_df['min_cc']
comile0_df['max_cc_overhead'] = comile0_df['max_noncc'] / comile0_df['max_cc']
# 결과 확인
#print(comile0_df[['model_path', 'max_num_seqs', 'mean_noncc', 'mean_cc', 'cc_overhead']].head())
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
print(comile0_df.columns)
print(comile0_df[['model_path','max_num_seqs','mean_cc','cv_cc']])

Index(['model_path', 'max_num_seqs', 'mean_noncc', 'min_noncc', 'max_noncc',
       'std_dev_noncc', 'cv_noncc', 'mean_cc', 'min_cc', 'max_cc',
       'std_dev_cc', 'cv_cc', 'cc_overhead', 'min_cc_overhead',
       'max_cc_overhead'],
      dtype='object')
                model_path  max_num_seqs      mean_cc     cv_cc
0  meta-llama/Llama-3.1-8B             4   371.510000  0.029444
1  meta-llama/Llama-3.1-8B             8   718.896667  0.032666
2  meta-llama/Llama-3.1-8B            16  1462.860000  0.029839
3  meta-llama/Llama-3.1-8B            32  2676.533333  0.025293

In [22]:
import pandas as pd
from IPython.display import display

# 두 개의 CSV 파일 읽기
df1 = pd.read_csv("vllm_offline_compile0_cc_min_and_max.csv")
df2 = pd.read_csv("vllm_offline_compile0_noncc_min_and_max.csv")

# 병합
vllm_offline_compile0_df = pd.merge(df1, df2, on=['model_path', 'max_num_seqs'], how='inner')

# 오버헤드 계산
vllm_offline_compile0_df['cc_overhead'] = vllm_offline_compile0_df['mean_noncc'] / vllm_offline_compile0_df['mean_cc']
vllm_offline_compile0_df['min_cc_overhead'] = vllm_offline_compile0_df['min_noncc'] / vllm_offline_compile0_df['min_cc']
vllm_offline_compile0_df['max_cc_overhead'] = vllm_offline_compile0_df['max_noncc'] / vllm_offline_compile0_df['max_cc']



# 표 형태로 출력
display(vllm_offline_compile0_df[['model_path', 'max_num_seqs', 'mean_cc', 
                               'mean_noncc','cv_cc', 'cv_noncc','cc_overhead']])

,model_path,max_num_seqs,mean_cc,mean_noncc,cv_cc,cv_noncc,cc_overhead
0,meta-llama/Llama-3.1-8B,4,371.510000,525.090000,0.029444,0.014759,1.413394
1,meta-llama/Llama-3.1-8B,8,718.896667,1034.156667,0.032666,0.008956,1.438533
2,meta-llama/Llama-3.1-8B,16,1462.860000,2003.163333,0.029839,0.011662,1.369347
3,meta-llama/Llama-3.1-8B,32,2676.533333,3754.923333,0.025293,0.003346,1.402905

# SGLang CG+TC

In [7]:
import pandas as pd
# 개별 CSV 파일 읽기
df1 = pd.read_csv("./amd/sglang_offline_nps4_cc_5000_2025-11-11/sglang_offline_nps4_cc_2025-11-11.csv")
df2 = pd.read_csv("./amd/sglang_offline_nps4_cc_5000_2025-11-17/sglang_offline_nps4_cc_2025-11-17.csv")

# 리스트에 추가
df_list = [df1, df2]

# 병합
merged_df = pd.concat(df_list, ignore_index=True)

output_csv = "./sglang_offline_compile1_cc_min_and_max.csv"
# 저장
merged_df.to_csv(output_csv, index=False)

In [8]:
import pandas as pd

# CSV 파일 읽기
df = pd.read_csv("./sglang_offline_compile1_cc_min_and_max.csv")


# 그룹화 및 통계 집계
grouped = df.groupby(['model_path', 'max_num_seqs'])['total_token_throughput'].agg(
    mean_cc='mean',
    min_cc='min',
    max_cc='max',
    std_dev_cc='std',
    cv_cc=coefficient_of_variation
).reset_index()

# 결과 저장
grouped.to_csv("sglang_offline_compile1_cc_min_and_max.csv", index=False)

In [5]:
import pandas as pd

# CSV 파일 읽기
df = pd.read_csv("sglang_offline_nps4_noncc_5000_2025-11-11/sglang_offline_nps4_noncc_2025-11-11.csv")

# 그룹화 및 통계 집계
grouped = df.groupby(['model_path', 'max_num_seqs'])['total_token_throughput'].agg(
    mean_noncc='mean',
    min_noncc='min',
    max_noncc='max',
    std_dev_noncc='std',
    cv_noncc=coefficient_of_variation
).reset_index()

# 결과 저장
grouped.to_csv("sglang_offline_compile1_noncc_min_and_max.csv", index=False)

In [9]:
import pandas as pd
from IPython.display import display


# 두 개의 CSV 파일 읽기
df1 = pd.read_csv("sglang_offline_compile1_noncc_min_and_max.csv")
df2 = pd.read_csv("sglang_offline_compile1_cc_min_and_max.csv")

# 병합
sglang_offline_compile0_df = pd.merge(df1, df2, on=['model_path', 'max_num_seqs'], how='inner')

# 오버헤드 계산
sglang_offline_compile0_df['cc_overhead'] = sglang_offline_compile0_df['mean_noncc'] / sglang_offline_compile0_df['mean_cc']
sglang_offline_compile0_df['min_cc_overhead'] = sglang_offline_compile0_df['min_noncc'] / sglang_offline_compile0_df['min_cc']
sglang_offline_compile0_df['max_cc_overhead'] = sglang_offline_compile0_df['max_noncc'] / sglang_offline_compile0_df['max_cc']



# 표 형태로 출력
display(sglang_offline_compile0_df[['model_path', 'max_num_seqs', 'mean_cc', 
                               'mean_noncc','cv_cc', 'cv_noncc','cc_overhead']])

,model_path,max_num_seqs,mean_cc,mean_noncc,cv_cc,cv_noncc,cc_overhead
0,meta-llama/Llama-3.1-8B,4,665.200,827.09,NaN,NaN,1.243370
1,meta-llama/Llama-3.1-8B,8,1196.910,1616.46,NaN,NaN,1.350528
2,meta-llama/Llama-3.1-8B,16,2048.770,3028.47,0.109809,NaN,1.478189
3,meta-llama/Llama-3.1-8B,32,3956.395,5430.21,0.128469,NaN,1.372515