In [1]:
def coefficient_of_variation(x):
    return x.std() / x.mean() if x.mean() != 0 else 0

In [9]:
import pandas as pd

# CSV 파일 읽기
df = pd.read_csv("./intel/vllm_offline_nps4_offload_noncc_5000_2025-11-25/vllm_offline_nps4_noncc_2025-11-25.csv")


# 그룹화 및 통계 집계
grouped = df.groupby(['model_path', 'max_num_seqs'])['total_token_throughput'].agg(
    mean_noncc='mean',
    min_noncc='min',
    max_noncc='max',
    std_dev_noncc='std',
    cv_noncc=coefficient_of_variation
).reset_index()

# 결과 저장
grouped.to_csv("vllm_tdx_offload_noncc_min_and_max.csv", index=False)
display(grouped)

,model_path,max_num_seqs,mean_noncc,min_noncc,max_noncc,std_dev_noncc,cv_noncc
0,meta-llama/Llama-3.1-8B,512,3301.37,3295.67,3307.07,8.061017,0.002442
1,meta-llama/Llama-3.1-8B,1024,3240.04,3228.00,3252.08,17.027131,0.005255
2,meta-llama/Llama-3.1-8B,2048,3070.41,3067.21,3073.61,4.525483,0.001474
3,meta-llama/Llama-3.1-8B,4096,2651.28,2651.28,2651.28,NaN,NaN
4,meta-llama/Llama-3.1-8B,8192,376.92,376.92,376.92,NaN,NaN

In [14]:
import pandas as pd

# CSV 파일 읽기
df = pd.read_csv("./intel/vllm_offline_nps4_offload_cc_5000_2025-11-26/vllm_offline_nps4_cc_2025-11-26.csv")


# 그룹화 및 통계 집계
grouped = df.groupby(['model_path', 'max_num_seqs'])['total_token_throughput'].agg(
    mean_cc='mean',
    min_cc='min',
    max_cc='max',
    std_dev_cc='std',
    cv_cc=coefficient_of_variation
).reset_index()

# 결과 저장
grouped.to_csv("vllm_tdx_offload_cc_min_and_max.csv", index=False)
display(grouped)

,model_path,max_num_seqs,mean_cc,min_cc,max_cc,std_dev_cc,cv_cc
0,meta-llama/Llama-3.1-8B,512,941.30,941.30,941.30,NaN,NaN
1,meta-llama/Llama-3.1-8B,1024,1182.37,1174.00,1190.74,11.836968,0.010011
2,meta-llama/Llama-3.1-8B,2048,1051.72,1038.86,1064.58,18.186786,0.017292
3,meta-llama/Llama-3.1-8B,4096,763.20,763.20,763.20,NaN,NaN

In [10]:
import pandas as pd

# CSV 파일 읽기
df = pd.read_csv("./intel/vllm_offline_nps4_nooffload_noncc_5000_2025-11-26/vllm_offline_nps4_noncc_2025-11-26.csv")


# 그룹화 및 통계 집계
grouped = df.groupby(['model_path', 'max_num_seqs'])['total_token_throughput'].agg(
    mean_noncc='mean',
    min_noncc='min',
    max_noncc='max',
    std_dev_noncc='std',
    cv_noncc=coefficient_of_variation
).reset_index()

# 결과 저장
grouped.to_csv("vllm_tdx_nooffload_noncc_min_and_max.csv", index=False)
display(grouped)

,model_path,max_num_seqs,mean_noncc,min_noncc,max_noncc,std_dev_noncc,cv_noncc
0,meta-llama/Llama-3.1-8B,512,4319.463333,4296.82,4360.58,35.669068,0.008258
1,meta-llama/Llama-3.1-8B,1024,3999.703333,3968.30,4040.30,36.869880,0.009218
2,meta-llama/Llama-3.1-8B,2048,3850.633333,3840.57,3856.91,8.803581,0.002286
3,meta-llama/Llama-3.1-8B,4096,3572.900000,3563.83,3581.12,8.676284,0.002428

In [6]:
import pandas as pd

# CSV 파일 읽기
df = pd.read_csv("./intel/vllm_offline_nps4_nooffload_cc_5000_2025-11-26/vllm_offline_nps4_cc_2025-11-26.csv")


# 그룹화 및 통계 집계
grouped = df.groupby(['model_path', 'max_num_seqs'])['total_token_throughput'].agg(
    mean_cc='mean',
    min_cc='min',
    max_cc='max',
    std_dev_cc='std',
    cv_cc=coefficient_of_variation
).reset_index()

# 결과 저장
grouped.to_csv("vllm_tdx_nooffload_cc_min_and_max.csv", index=False)
display(grouped)

,model_path,max_num_seqs,mean_cc,min_cc,max_cc,std_dev_cc,cv_cc
0,meta-llama/Llama-3.1-8B,512,4156.97,4156.97,4156.97,NaN,NaN
1,meta-llama/Llama-3.1-8B,1024,3847.50,3847.50,3847.50,NaN,NaN
2,meta-llama/Llama-3.1-8B,2048,3694.28,3694.28,3694.28,NaN,NaN
3,meta-llama/Llama-3.1-8B,4096,3462.25,3462.25,3462.25,NaN,NaN

In [15]:
import pandas as pd

# 두 개의 CSV 파일 읽기
df1 = pd.read_csv("vllm_tdx_offload_cc_min_and_max.csv")
df2 = pd.read_csv("vllm_tdx_offload_noncc_min_and_max.csv")

vllm_dtx_df = pd.merge(df1, df2, on=['model_path', 'max_num_seqs'], how='inner')
# cc_overhead 열 추가: mean_noncc / mean_cc
vllm_dtx_df['cc_overhead'] = vllm_dtx_df['mean_noncc'] / vllm_dtx_df['mean_cc']
vllm_dtx_df['min_cc_overhead'] = vllm_dtx_df['min_noncc'] / vllm_dtx_df['min_cc']
vllm_dtx_df['max_cc_overhead'] = vllm_dtx_df['max_noncc'] / vllm_dtx_df['max_cc']
# 결과 확인
#print(vllm_dtx_df[['model_path', 'max_num_seqs', 'mean_noncc', 'mean_cc', 'cc_overhead']].head())
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
print(vllm_dtx_df.columns)
print(vllm_dtx_df[['model_path','max_num_seqs','mean_noncc','cv_cc']])
display(vllm_dtx_df)

Index(['model_path', 'max_num_seqs', 'mean_cc', 'min_cc', 'max_cc',
       'std_dev_cc', 'cv_cc', 'mean_noncc', 'min_noncc', 'max_noncc',
       'std_dev_noncc', 'cv_noncc', 'cc_overhead', 'min_cc_overhead',
       'max_cc_overhead'],
      dtype='object')
                model_path  max_num_seqs  mean_noncc     cv_cc
0  meta-llama/Llama-3.1-8B           512     3301.37       NaN
1  meta-llama/Llama-3.1-8B          1024     3240.04  0.010011
2  meta-llama/Llama-3.1-8B          2048     3070.41  0.017292
3  meta-llama/Llama-3.1-8B          4096     2651.28       NaN

,model_path,max_num_seqs,mean_cc,min_cc,max_cc,std_dev_cc,cv_cc,mean_noncc,min_noncc,max_noncc,std_dev_noncc,cv_noncc,cc_overhead,min_cc_overhead,max_cc_overhead
0,meta-llama/Llama-3.1-8B,512,941.30,941.30,941.30,NaN,NaN,3301.37,3295.67,3307.07,8.061017,0.002442,3.507245,3.501190,3.513301
1,meta-llama/Llama-3.1-8B,1024,1182.37,1174.00,1190.74,11.836968,0.010011,3240.04,3228.00,3252.08,17.027131,0.005255,2.740293,2.749574,2.731142
2,meta-llama/Llama-3.1-8B,2048,1051.72,1038.86,1064.58,18.186786,0.017292,3070.41,3067.21,3073.61,4.525483,0.001474,2.919418,2.952477,2.887157
3,meta-llama/Llama-3.1-8B,4096,763.20,763.20,763.20,NaN,NaN,2651.28,2651.28,2651.28,NaN,NaN,3.473899,3.473899,3.473899

In [16]:
import pandas as pd

# 두 개의 CSV 파일 읽기
df1 = pd.read_csv("vllm_tdx_nooffload_cc_min_and_max.csv")
df2 = pd.read_csv("vllm_tdx_nooffload_noncc_min_and_max.csv")

vllm_dtx_df = pd.merge(df1, df2, on=['model_path', 'max_num_seqs'], how='inner')
# cc_overhead 열 추가: mean_noncc / mean_cc
vllm_dtx_df['cc_overhead'] = vllm_dtx_df['mean_noncc'] / vllm_dtx_df['mean_cc']
vllm_dtx_df['min_cc_overhead'] = vllm_dtx_df['min_noncc'] / vllm_dtx_df['min_cc']
vllm_dtx_df['max_cc_overhead'] = vllm_dtx_df['max_noncc'] / vllm_dtx_df['max_cc']
# 결과 확인
#print(vllm_dtx_df[['model_path', 'max_num_seqs', 'mean_noncc', 'mean_cc', 'cc_overhead']].head())
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
print(vllm_dtx_df.columns)
print(vllm_dtx_df[['model_path','max_num_seqs','mean_noncc','cv_cc']])
display(vllm_dtx_df)

Index(['model_path', 'max_num_seqs', 'mean_cc', 'min_cc', 'max_cc',
       'std_dev_cc', 'cv_cc', 'mean_noncc', 'min_noncc', 'max_noncc',
       'std_dev_noncc', 'cv_noncc', 'cc_overhead', 'min_cc_overhead',
       'max_cc_overhead'],
      dtype='object')
                model_path  max_num_seqs   mean_noncc  cv_cc
0  meta-llama/Llama-3.1-8B           512  4319.463333    NaN
1  meta-llama/Llama-3.1-8B          1024  3999.703333    NaN
2  meta-llama/Llama-3.1-8B          2048  3850.633333    NaN
3  meta-llama/Llama-3.1-8B          4096  3572.900000    NaN

,model_path,max_num_seqs,mean_cc,min_cc,max_cc,std_dev_cc,cv_cc,mean_noncc,min_noncc,max_noncc,std_dev_noncc,cv_noncc,cc_overhead,min_cc_overhead,max_cc_overhead
0,meta-llama/Llama-3.1-8B,512,4156.97,4156.97,4156.97,NaN,NaN,4319.463333,4296.82,4360.58,35.669068,0.008258,1.039089,1.033642,1.048980
1,meta-llama/Llama-3.1-8B,1024,3847.50,3847.50,3847.50,NaN,NaN,3999.703333,3968.30,4040.30,36.869880,0.009218,1.039559,1.031397,1.050110
2,meta-llama/Llama-3.1-8B,2048,3694.28,3694.28,3694.28,NaN,NaN,3850.633333,3840.57,3856.91,8.803581,0.002286,1.042323,1.039599,1.044022
3,meta-llama/Llama-3.1-8B,4096,3462.25,3462.25,3462.25,NaN,NaN,3572.900000,3563.83,3581.12,8.676284,0.002428,1.031959,1.029339,1.034333